export const CONVENIO_REGISTRY = [
  {
    id: "uocra",
    label: "UOCRA",
    cct: "76/75",
    activity: "Construcción",
    icon: "briefcase",
    iconTone: "blue",
    source: "eSueldos_UOCRA_v5_2026.html",
    description: "Construcción, jornales, adicionales de obra y liquidación por horas.",
    status: "active",
    updatedAt: "2025-05-18",
  },
  {
    id: "afa",
    label: "AFA",
    cct: "553/09",
    activity: "Fútbol y administración",
    icon: "bag",
    iconTone: "orange",
    source: "AFA_v5.html",
    description: "Escalas salariales, adicionales frecuentes y validaciones administrativas.",
    status: "active",
    updatedAt: "2025-05-15",
  },
  {
    id: "clinicas",
    label: "Clínicas y Sanatorios",
    cct: "122/75",
    activity: "Clínicas y Sanatorios",
    icon: "heart",
    iconTone: "pink",
    source: "ClinicaySanatorios_v5.html",
    description: "Sector salud con categorías FATSA, presentismo y adicionales específicos.",
    status: "active",
    updatedAt: "2025-05-12",
  },
  {
    id: "callcenter",
    label: "Call Center",
    cct: "781/20",
    activity: "Atención telefónica",
    icon: "chat",
    iconTone: "violet",
    source: "CallCenter_v5.html",
    description: "Jornada, categorías y conceptos variables para atención telefónica.",
    status: "active",
    updatedAt: "2025-05-10",
  },
  {
    id: "gimnasios",
    label: "Gimnasios",
    cct: "738/16",
    activity: "Actividad física",
    icon: "shield",
    iconTone: "green",
    source: "Gimnasios_v5.html",
    description: "Roles, jornada, adicionales y liquidación mensual para actividad física.",
    status: "review",
    updatedAt: "2025-05-08",
  },
];

window.CONVENIO_REGISTRY = CONVENIO_REGISTRY;
